general:
    train_dir: "data/skin-lesion/kaggle/archive/train/train/"
    test_dir: "data/skin-lesion/kaggle/archive/train/val/"
    num_workers: 4
    gpu: [0]
    dir_to_save: "saved_models/"
    seed: 2021
    nepune_project_name: 'agnieszka-mikolajczyk/skin-lesion'
    accumulate_grad_batches: 4
    epochs: 2

mask_dirs:
    source_dir: "data/skin-lesion/aug/source_merged/"
    train: 
      hair_and_ruler: "data/skin-lesion/aug/mask_merged/"
      frame: "data/skin-lesion/aug/frames-aug/"
    test:
      hair_short: "data/skin-lesion/aug/hair-short/"
      hair_medium: "data/skin-lesion/aug/hair-medium/"
      hair_dense: "data/skin-lesion/aug/hair-dense/"
      ruler: "data/skin-lesion/aug/hair-ruler/"
      frame: "data/skin-lesion/aug/frame/"
    
training_plan:
    architectures: 
      names: ["vit_base_patch16_224"]
      input_sizes: [224, 224, 224]
      batch_sizes: [16, 16, 16]
    probabilities: [0.25, 0.5, 0.75, 1.0]
    augmentations: ["hair_and_ruler", "frame", "normal"]

cbi_plan:
    architectures: 
      names: ["efficientnet_b2",'densenet121',"vit_base_patch16_224"]
      input_sizes: [224, 256, 224]
      batch_sizes: [4, 4, 4]
    dir_to_saved_models: "saved_models/"
    augmentations: ["frame", "hair_short", "hair_medium", "hair_dense","ruler"]
    results_path: "cbi_results.tsv"
    save_preds_dir: "results/"
    masks_to_test: [0, 1, 2, 3, 4]
